repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: [--fix]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        # Keep in sync with pyproject.toml [tool.tox.env.typecheck] deps
        additional_dependencies: [aiosqlite, python-telegram-bot, python-dotenv, pytest, pytest-asyncio]
        args: [--strict]
